name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno run --allow-net --allow-env --allow-read --allow-sys index.ts"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "kiratrizon-express-lar-16"
          entrypoint: "./index.ts"
          root: "./"
          
          
